spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: payment
    password: payment
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_updates: true #помог избавиться от deadlock для optimistic lock
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics

  endpoint:
    health:
      show-details: always